# Generated by Django 6.0.3 on 2026-03-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('help_type', models.CharField(max_length=100, verbose_name='Тип помощи')),
                ('description', models.TextField(verbose_name='Описание ситуации')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('processing', 'В обработке'), ('done', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('title_kz', models.CharField(max_length=100, verbose_name='Название (KZ)')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория льгот',
                'verbose_name_plural': 'Категории льгот',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(max_length=100, verbose_name='Направление')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('inactive', 'Неактивный')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='shield', max_length=50, verbose_name='Иконка (ключ из ICONS)')),
                ('badge_ru', models.CharField(max_length=50, verbose_name='Метка (RU)')),
                ('badge_kz', models.CharField(max_length=50, verbose_name='Метка (KZ)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('title_kz', models.CharField(max_length=200, verbose_name='Заголовок (KZ)')),
                ('short_desc_ru', models.TextField(verbose_name='Краткое описание (RU)')),
                ('short_desc_kz', models.TextField(verbose_name='Краткое описание (KZ)')),
                ('amount_ru', models.TextField(verbose_name='Размер выплат (RU)')),
                ('amount_kz', models.TextField(verbose_name='Размер выплат (KZ)')),
                ('who_ru', models.TextField(verbose_name='Кому положено (RU)')),
                ('who_kz', models.TextField(verbose_name='Кому положено (KZ)')),
                ('docs_ru', models.TextField(verbose_name='Документы (RU, через запятую или HTML)')),
                ('docs_kz', models.TextField(verbose_name='Документы (KZ)')),
                ('how_ru', models.TextField(verbose_name='Как получить (RU)')),
                ('how_kz', models.TextField(verbose_name='Как получить (KZ)')),
                ('source', models.URLField(blank=True, null=True, verbose_name='Ссылка на источник')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='social_support.benefitcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Льгота',
                'verbose_name_plural': 'Льготы',
            },
        ),
    ]
