# Generated by Django 6.0.3 on 2026-03-31 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Волонтер', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.AddField(
            model_name='application',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Заметка специалиста'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('processing', 'В обработке'), ('assigned', 'Специалист назначен'), ('done', 'Завершена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='docs_ru',
            field=models.TextField(verbose_name='Документы (RU)'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(default='shield', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('iin', models.CharField(blank=True, max_length=12, verbose_name='ИИН')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kz', 'Қазақша')], default='ru', max_length=2, verbose_name='Язык')),
                ('avatar_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Цвет аватара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
