# Generated by Django 6.0.3 on 2026-03-31 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_support', '0002_alter_application_options_alter_volunteer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Заголовок (RU)')),
                ('title_kz', models.CharField(max_length=300, verbose_name='Заголовок (KZ)')),
                ('body_ru', models.TextField(verbose_name='Текст (RU)')),
                ('body_kz', models.TextField(verbose_name='Текст (KZ)')),
                ('category', models.CharField(choices=[('news', 'Новости'), ('announcement', 'Объявление'), ('law', 'Законодательство'), ('event', 'Мероприятие')], default='news', max_length=20, verbose_name='Категория')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на источник')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='social_support.volunteer', verbose_name='Назначенный волонтёр'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='cases_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Завершено дел'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('psychologist', 'Психолог'), ('lawyer', 'Юрист'), ('digital', 'Цифровой волонтёр'), ('social', 'Социальный волонтёр'), ('other', 'Другое')], default='social', max_length=20, verbose_name='Направление'),
        ),
    ]
